# Generated by Django 4.2.20 on 2026-09-01 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voice_notes', '0008_voicenote_trace_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ja', 'Japanese'), ('ko', 'Korean'), ('zh', 'Chinese')], max_length=10)),
                ('source_language', models.CharField(blank=True, default='', help_text="Language of the transcript at translation time (detected code or 'auto').", max_length=10)),
                ('text', models.TextField(blank=True, default='')),
                ('segments', models.JSONField(blank=True, default=list, help_text="[{'segment_id': int, 'text': str}] aligned to TranscriptionSegment rows; empty when the note has no segments.")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('provider', models.CharField(blank=True, default='', max_length=40)),
                ('model', models.CharField(blank=True, default='', max_length=80)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=20)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voice_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='voice_notes.voicenote')),
            ],
            options={
                'ordering': ['target_language'],
            },
        ),
        migrations.AddConstraint(
            model_name='notetranslation',
            constraint=models.UniqueConstraint(fields=('voice_note', 'target_language'), name='unique_translation_per_note_language'),
        ),
    ]
