# Generated by Django 4.2.16 on 2025-08-11 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_language', models.CharField(choices=[('en-US', 'English (US)'), ('en-GB', 'English (GB)'), ('es-ES', 'Spanish'), ('fr-FR', 'French'), ('de-DE', 'German'), ('it-IT', 'Italian'), ('pt-PT', 'Portuguese'), ('ja-JP', 'Japanese'), ('ko-KR', 'Korean'), ('zh-CN', 'Chinese (Simplified)')], default='en-US', max_length=10)),
                ('audio_quality', models.CharField(choices=[('low', 'Low (8kHz)'), ('medium', 'Medium (16kHz)'), ('high', 'High (44.1kHz)')], default='high', max_length=10)),
                ('storage_quota_mb', models.PositiveIntegerField(default=1000)),
                ('storage_used_mb', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
