# Generated by Django 4.2.20 on 2026-03-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='storage_used_mb',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
