# Generated by Django 4.2.20 on 2026-06-28 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('bug', 'Something is broken'), ('change', 'Change how something works'), ('feature', 'New capability')], default='bug', max_length=20)),
                ('body', models.TextField()),
                ('trace_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('needs_detail', 'Needs more detail'), ('submitted', 'Submitted'), ('issue_created', 'Issue created'), ('in_progress', 'Codex working'), ('shipped', 'Shipped'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('gate_reason', models.TextField(blank=True, default='')),
                ('github_issue_number', models.IntegerField(blank=True, null=True)),
                ('github_issue_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
