# Generated by Django 4.2.16 on 2025-08-11 18:02

import apps.voice_notes.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VoiceNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('transcription', models.TextField(blank=True)),
                ('audio_file', models.FileField(help_text='Allowed formats: wav, mp3, ogg, webm, m4a', upload_to=apps.voice_notes.models.audio_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['wav', 'mp3', 'ogg', 'webm', 'm4a'])])),
                ('duration', models.DurationField(blank=True, null=True)),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('language_detected', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ja', 'Japanese'), ('ko', 'Korean'), ('zh', 'Chinese'), ('auto', 'Auto-detect')], default='auto', max_length=10)),
                ('confidence_score', models.FloatField(blank=True, help_text='Transcription confidence (0.0-1.0)', null=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='voice_notes', to='voice_notes.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voice Note',
                'verbose_name_plural': 'Voice Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptionSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.FloatField(help_text='Segment start time in seconds')),
                ('end_time', models.FloatField(help_text='Segment end time in seconds')),
                ('text', models.TextField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('speaker_id', models.CharField(blank=True, help_text='Speaker identification', max_length=50)),
                ('voice_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='voice_notes.voicenote')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
