# Generated by Django 4.2.16 on 2025-08-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicenote',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
