# Generated by Django 4.2.20 on 2026-03-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_notes', '0002_alter_voicenote_title'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transcriptionsegment',
            index=models.Index(fields=['voice_note', 'start_time'], name='voice_notes_voice_n_44e172_idx'),
        ),
        migrations.AddIndex(
            model_name='voicenote',
            index=models.Index(fields=['user', '-created_at'], name='voice_notes_user_id_a75345_idx'),
        ),
        migrations.AddIndex(
            model_name='voicenote',
            index=models.Index(fields=['user', 'status'], name='voice_notes_user_id_86ebf9_idx'),
        ),
    ]
