# Generated by Django 4.2.20 on 2026-03-23 01:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_notes', '0003_transcriptionsegment_voice_notes_voice_n_44e172_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicenote',
            name='confidence_score',
            field=models.FloatField(blank=True, help_text='Transcription confidence (0.0-1.0)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
