# Generated by Django 4.2.20 on 2026-06-28 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voice_notes', '0006_folder_voicenote_folder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Original diarization label, e.g. 'Speaker 1'", max_length=50)),
                ('name', models.CharField(help_text='Editable display name', max_length=100)),
                ('voice_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='voice_notes.voicenote')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.AddConstraint(
            model_name='speaker',
            constraint=models.UniqueConstraint(fields=('voice_note', 'label'), name='unique_speaker_per_note'),
        ),
    ]
