# Generated by Django 4.2.20 on 2026-06-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_notes', '0007_speaker_speaker_unique_speaker_per_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicenote',
            name='trace_id',
            field=models.CharField(blank=True, default='', help_text="End-to-end trace/correlation id linking this note's frontend request, transcription task, and external API calls in the logs.", max_length=64),
        ),
    ]
